### ISSUE TITLE
Does not switch inside yaml files

### ISSUE THREAD

**Issue by mobilesfinks** [atom/toggle-quotes#63]
### Description

It does not switch quotes in yaml files, but at the same time it work in the newly created file with the JS extension.

Disable yaml linter and extensions - not helped

Example from yaml file (some.yaml) (Not Work)
```
    volumes: 
      etcdbackup: 
        pvc: etcdbackup
        size: 50Gi
        accessModes: ["ReadWriteOnce"]
```

Example from JS file (test.js) (Worked)
```
function test () { return "hello"; }
    size: 50Gi
    accessModes: ['ReadWriteOnce']

```

### Versions

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 2.7.12
git 2.7.4

toggle-quotes 1.1.1
